# Generated by Django 3.0.8 on 2022-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('service_render', models.CharField(max_length=100)),
                ('cloth_type', models.TextField(max_length=100)),
                ('total_number_of_cloth', models.CharField(max_length=100)),
                ('amount_charged', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('collected', 'COLLECTED')], default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
