# Generated by Django 3.0.8 on 2021-04-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=2000)),
                ('reqiured_knowledge', models.CharField(max_length=2000)),
                ('education_experience', models.CharField(max_length=2000)),
                ('salary', models.CharField(max_length=2000)),
                ('experience', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='')),
                ('do_you_have_serious_health_ailment', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('disability', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('do_you_use_hearing_aids', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('do_you_use_glasses_or_lenses_for_your_eyesight', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('have_yo_beign_dependent_on_drugs_or_alcohol', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('qualification', models.ManyToManyField(to='accounts.Qualification')),
            ],
        ),
    ]
