# Generated by Django 3.0.8 on 2021-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_qualification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
