# Generated by Django 3.0.8 on 2021-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_qualification_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='Deadline',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
