# Generated by Django 3.0.8 on 2021-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210421_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='qualification',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='disability',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='do_you_have_serious_health_ailment',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='do_you_use_glasses_or_lenses_for_your_eyesight',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='do_you_use_hearing_aids',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='have_you_beign_dependent_on_drugs_or_alcohol',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='marital_status',
            field=models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('divorced', 'DIVORCED')], max_length=200),
        ),
    ]
