# Generated by Django 3.0.8 on 2022-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=400)),
                ('job_type', models.CharField(default='', max_length=100)),
                ('lga', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=11)),
                ('date_of_appointment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
