# Generated by Django 3.0.8 on 2022-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income_for_today', models.CharField(max_length=200)),
                ('total_profit_for_today', models.CharField(max_length=200)),
                ('total_laundry_claimed_today', models.CharField(max_length=200)),
                ('total_customer_today', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
